version: '3'

services:

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      CLIENT_HOSTS:
      JWT_SECRET:
      NODE_ENV:
      PRISMA_ENDPOINT: http://prisma:4477
      PRISMA_SERVICE:
      PRISMA_STAGE:
      PRISMA_SERVICE_SECRET:
    command: npm run dev
    volumes:
      - .:/usr/app

  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "4477:4477"
    environment:
      PRISMA_CONFIG: |
        port: 4477
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: